# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e13c1fa9471238a23cc1a4abfedfe67765ea8ee0312e992b49f42b85c8f9a944a52c8d74add8ef13b9396ea5ea40ed1565e5749a28d3653cd5da963ecbf85b2b

test:
  secret_key_base: fc8e69f10884aa652c1ca0c348e73e5c76dc7be518d670780ddebecb4ca0180dd6c469e80d6a0a41c0ec83c9d4983281f7c82667226049f5bcc7850f06fcf845

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
